import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Nav from "../components/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authLinks = [
    { href: "/", title: "로그아웃" },
    { href: "/user", title: "내 페이지" },
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav link={authLinks} />
        {children}
      </body>
    </html>
  );
}
