import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Smile } from "lucide-react";
import { getIronSessionData } from "@/lib/session";
import Nav from "./components/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Shop App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 루트 레이아웃에서 세션 받아와서
  // 있는지 없는지에 따라서 nav 다르게 그리기
  const session = await getIronSessionData();
  console.log("session", session);
  const noAuthLinks = [
    { href: "/login", title: "로그인" },
    { href: "/register", title: "회원가입" },
    { href: "/board", title: "게시판" },
  ];
  const authLinks = [
    { href: "/logout", title: "로그아웃" },
    { href: "/user", title: "내 페이지" },
    { href: "/board", title: "게시판" },
  ];
  const links = session.isLoggedIn === true ? authLinks : noAuthLinks;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav link={links} />
        {children}
        <footer className="flex justify-center items-end  py-5">
          All right reserved. <Smile />
        </footer>
      </body>
    </html>
  );
}
