import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import LinkComponents from "../components/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const noAuthLinks = [
    { href: "/login", title: "로그인" },
    { href: "/register", title: "회원가입" },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LinkComponents link={noAuthLinks} />
        {children}
      </body>
    </html>
  );
}
