import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import LinkComponents from "../components/nav";
import { Smile } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Shop App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const noAuthLinks = [
    { href: "/login", title: "로그인" },
    { href: "/register", title: "회원가입" },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LinkComponents link={noAuthLinks} />
        {children}
        <footer className="flex justify-center items-end  py-5">
          All right reserved. <Smile />
        </footer>
      </body>
    </html>
  );
}
